language: php

php:
  - 5.3
  - 5.4
  - 5.5

env:
  - DOCTRINE_VERSION: 2.1.*
  - DOCTRINE_VERSION: 2.2.*
  - DOCTRINE_VERSION: 2.3.*
  - DOCTRINE_VERSION: 2.4.*@dev

before_script:
  - composer require --dev doctrine/orm:${DOCTRINE_VERSION}

notifications:
  email: matthiasnoback@gmail.com